### ISSUE TITLE
[transform] postcssify transform

### ISSUE THREAD

**Issue by youzi** [vigour-io/postcssify#16]
We have a work-in-progress version of the postcssify transform in feature/transform.

The transform attempts to **handle everything within the scope of the transform**, without needing using the transform globally or needing a separate plugin.

It tracks all the files that the transform is applied on and attempts to bundle when all files have been parsed/ handled.

We are now at a stage where we can make this transform really sweet by adding some nice options. Options I'm thinking about:
- `output` define where to leave the output (if `true` inject?)
- `plugins` define plugins to apply on each file (separately)
- `bundlePlugins` define plugins to apply on the entire bundle

Not sure about the keys for the options (especially `bundlePlugins` ofc)

/cc @vigour-io/front-end @shawninder

**Comment by shawninder** [comment]
yeah I originally had `filePlugins` and `plugin`, but I also thought we might want to find something better... I'll think about it.

**Comment by shawninder** [comment]
The transform version is the new #master, replacing the plugin approach I originally had.

**Comment by shawninder** [comment]
The rest of this issue is covered in #2 so I'm closing this one
