### ISSUE TITLE
Postcssify breaking extension resolution

### ISSUE THREAD

**Issue by kevindente** [vigour-io/postcssify#30]
For some reason when I include postcssify as a browerify transform, it breaks the ability to resolve .jsx files without the extension (eg import File from 'File" stops working, I have to do import File from 'File.jsx').  If I take out postcssify it starts working again (I've specific .jsx in the --extension option for browserify). Any idea why this would be?

**Comment by kevindente** [comment]
Traced through the code a bit, and it looks like collect() is calling resolve(), but not specifying the extensions in the options, so resolve fails on the jsx file.

**Comment by youzi** [comment]
@kevindente Thanks for pointing out this issue and if you'd like to make a modification, you are welcome.

This module currently needs **a lot** of work, and is currently in the very minimal state that we can use it internally.
