### ISSUE TITLE
Not working with require-globify

### ISSUE THREAD

**Issue by kevindente** [vigour-io/postcssify#33]
For some reason glob-based requires registered with require-globify aren't being picked by postcssify.

**Comment by kevindente** [comment]
I think this may be because the code is assuming one require per line, and require-globify puts a bunch of requires on the same line when it expands the glob

**Comment by jimdebeer** [comment]
@kevindente that sounds like the problem (uses linereader) @mstdokumaci would you care to pick this tool up? Think @youzi does not really have time at all next few months

**Comment by jimdebeer** [comment]
and thanks for pointing this out @kevindente
