### ISSUE TITLE
filePlugins not getting called

### ISSUE THREAD

**Issue by LaurieSReynolds** [vigour-io/postcssify#35]
In a small test project, I am calling postcssify with the postcss-advanced-variables plugin and it is not getting called.  The resulting css still contains the variable definition.

```
"start": "browserify ./src/client.js -d $npm_package_config_browserify_transforms --extension=jsx -o public/bundle.js",

"browserify_transforms": "-t babelify -t require-globify -g [postcssify  --filePlugins postcss-advanced-variables -o public//bundle.css ]"
```

[Github test project:  https://github.com/LaurieSReynolds/react-browserify-boilerplate](https://github.com/LaurieSReynolds/react-browserify-boilerplate)

---

If I hard code the plugin into the postcssify index.js array of processors, the plugin is invoked and the variable is replaced with the correct value.

https://github.com/vigour-io/postcssify/blob/master/lib/index.js

---

I am using version 2.5.0 of postcssify

---

How can I correctly specify postcss plugins?

**Comment by kevindente** [comment]
Looking through the code, it looks like the processor list is currently hard-coded. I have to assume this was a mistake, yes?

**Comment by jimdebeer** [comment]
I think the readme should be updated, there are zero config options atm

**Comment by jimdebeer** [comment]
@mstdokumaci could you perhaps do this?

**Comment by kevindente** [comment]
I'm sorry, is the intent here that you can't configure the postcss plugins? If so, I need to find a different transform to use.

**Comment by mstdokumaci** [comment]
Unfortunately we require and use only a few plugins and they are hard coded, we didn't implement it configurable. Sorry for the inconvenience.

**Comment by kevindente** [comment]
Would you accept a PR to implement the configuration stuff?

**Comment by mstdokumaci** [comment]
If you have time to implement it, sure it's all welcome.
